### ISSUE TITLE
(01) ticket - (03) validation

### ISSUE THREAD

**Issue by gilescope** [LukeMathWalker/build-your-own-jira-with-rust#17]
```
            // You should be seeing this error when trying to run this koan:
            //
            // error[E0616]: field `description` of struct `path_to_enlightenment::visibility::ticket::Ticket` is private
            // --> jira-wip/src/koans/01_ticket/04_visibility.rs:99:25
            //    |
            // 99 |              assert_eq!(ticket.description, "A description");
            //    |                         ^^^^^^^^^^^^^^^^^^
            //
            // If that is the case, comment the next line out and move on to the next koan!
            assert_eq!(ticket.description, "A description");
```
The above is all true, but I see this error without having `Add the necessary `pub` modifiers in the code above`... i.e. I made no modifications and it's instructing me to go to the next koan?

Also maybe be a bit more explicit on this step:
Once you have verified that it does not compile, =>
Once you have verified that the below does not compile,

**Comment by gilescope** [comment]
Also please use #[allow(unused_doc_comments)] as latest nightly grumbles about things like:
```
/// Field syntax: you use a dot to access the field of a struct.
assert_eq!(ticket_one.description, "A heart-breaking description");
```
(two slashes works fine)

**Comment by gilescope** [comment]
Go to definition of Ticket using rust analyser looks at lots of tickets - doesn't make it clear that recap::Ticket is the one you want. This is a failing of RA, but might trip some people up as there's a lot of Ticket definitions at that point.

**Comment by LukeMathWalker** [comment]
Ok, I think I fixed it :+1: 
Don't really know how to address the code navigation issue unfortunately :disappointed:

**Comment by jamiebrynes7** [comment]
FYIW, I found the Jetbrains plugin to be able to resolve the types fairly well

**Comment by gilescope** [comment]
Yep CLion's still the daddy for now. But the gap is closing fast.

Grep for: "This isn't our JIRA works"

**Comment by gilescope** [comment]
TicketDraft shouldn't really have a Status on it as it really is a status? I.e. everything starts as a Status::ToDo

**Comment by gilescope** [comment]
for 2_05 I think we could fill in the impls of TicketDraft and Ticket for them - they're tired by now and there's no doubt what goes in them really.

**Comment by gilescope** [comment]
I think it would be awesome if we could give them this: 

```
impl TicketPatch {
        fn apply(self, ticket: &mut Ticket) {
            if let Some(title) = self.title {
                ticket.title = title;
            }
            if let Some(description) = self.description {
                ticket.description = description;
            }
            if let Some(status) = self.status {
                ticket.status = status;
            }
        }
    }
```

and somehow point out that the method totally consumes the patch (i.e. it's taking ownership of self).

**Comment by LukeMathWalker** [comment]
> for 2_05 I think we could fill in the impls of TicketDraft and Ticket for them - they're tired by now and there's no doubt what goes in them really.

It's mostly for muscle memory, I think it's useful to just type it out for yourself a couple of times.

**Comment by gilescope** [comment]
for consistency it might be better to use todo!() everywhere rather than a mix of __ and todo!()

**Comment by LukeMathWalker** [comment]
todo!() unfortunately can only be used in function bodies, not for type signature and other wildly illegal omissions :grin:
