### ISSUE TITLE
Koan colored test outputs

### ISSUE THREAD

**Issue by CGMossa** [LukeMathWalker/build-your-own-jira-with-rust#21]
I don't know where this needs to go, but if 

```rust
fn run_tests(manifest_path: &Path, filter: Option<&str>) -> TestOutcome {
    let mut args: Vec<OsString> = vec![
        "test".into(),
        "--manifest-path".into(),
        manifest_path.into(),
        "-q".into(),
        "--color=always".into()
    ];
...
```
Then we get colored output. It is not the best ever, but it is something. I don't know where this actually needs to go with this `yansi` stuff.. So here's the suggestion.

**Comment by LukeMathWalker** [comment]
I used `yansi` to determine dynamically the value of the `color` flag - now it should return colored output when supported.
Thanks for flagging!
