### ISSUE TITLE
Minute feedback

### ISSUE THREAD

**Issue by CGMossa** [LukeMathWalker/build-your-own-jira-with-rust#22]
- In `05_type_as_constraints,rs` there is
```rust
    /// Has it been saved yet? Is it safe to unwrap whose `Option`s?
    /// That is unnecessary cognitive load and lead to errors down the line,
```
but maybe it should be
```rust
    /// Has it been saved yet? Is it safe to unwrap those `Option`s?
    /// That is unnecessary cognitive load and leads to errors down the line,
```
- In `06_results`, the example of using `Err(ValidationError(...` does not use the constructor `Err(ValidationError::new("Some error message")`.

Also, isn't 

```rust
    impl std::fmt::Display for ValidationError {
        fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            write!(f, "{}", self.0)
        }
    }
```
is supposed to be something like:
```rust
    impl std::fmt::Display for ValidationError {
        fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            write!(f, "{}", self.0)?;
            Ok(())
        }
    }
```
Maybe `write!` has changed, since `clippy` isn't saying anything.

**Comment by CGMossa** [comment]
And another thing, I think one should have these..

```rust
    impl FromStr for TicketTitle {
        type Err = ValidationError;

        fn from_str(s: &str) -> Result<Self, Self::Err> {
            Self::new(s.into())
        }
    }
```
and similarly 
```rust
    impl FromStr for TicketDescription {
        type Err = ValidationError;

        fn from_str(s: &str) -> Result<Self, Self::Err> {
            Self::new(s.into())
        }
    }
```

Because at first read, it seems more reasonable to have
```rust
        Edit {
            #[structopt(long)]
            ticket_id: TicketId,
            /// Status of the new ticket.
            #[structopt(long)]
            status: Option<Status>,
            #[structopt(long)]
            title: Option<TicketTitle>,
            #[structopt(long)]
            description: Option<TicketDescription>,
        },
```

`handle_command` is private, but should be public to be able to be used from `main.rs`.

**Comment by LukeMathWalker** [comment]
> Also, isn't
> 
> ```rust
>     impl std::fmt::Display for ValidationError {
>         fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
>             write!(f, "{}", self.0)
>         }
>     }
> ```
> 
> is supposed to be something like:
> 
> ```rust
>     impl std::fmt::Display for ValidationError {
>         fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
>             write!(f, "{}", self.0)?;
>             Ok(())
>         }
>     }
> ```
> 
> Maybe `write!` has changed, since `clippy` isn't saying anything.

I don't see why it is necessary to use the `?` operator - `write!` should be returning a `std::fmt::Result`, hence we can return it directly. What am I missing here?

**Comment by CGMossa** [comment]
Right, I figured it out now. It is necessary if you have multiple
write-invocation. Sorry, I have to retract that.
